### PR TITLE
upgrade to 1.25.0 and migrate to new authentication system

### PR DESCRIPTION
**Pull request by Roshick**
Fixes https://github.com/procore-oss/backstage-plugin-announcements/issues/249 and provides integration with the new authentication system.

### CODE REVIEW

**Comment by Roshick** [comment]
I'm currently stuck on creating an auth service instance for the standalone server. The mock service works when testing, but I don't think this is the way to go.

**Comment by gaelgoth** [comment]
Hello @Roshick ,
It's still a bit hacky, but you did try something like this: https://github.com/backstage/backstage/blob/master/plugins/notifications-backend/src/service/standaloneServer.ts#L117-L125

**Comment by Roshick** [comment]
Thanks a lot @gaelgoth, this seems to work! 

I'm gonna integrate my version with our backstage instance on Monday and if everything works as expected I'm gonna clean up the pull request.

**Comment by Roshick** [comment]
Had some spare time to test it and everything worked as expected (except 1 issue in the AnnouncementsPage which I didn't really understand https://github.com/procore-oss/backstage-plugin-announcements/pull/269/files#diff-0e0f6d17b627afa0b5395e7d82b8407d7d87595dd179f6a91e27db9405277acaL258, crashed the page if the ! was included but only in our instance, not in the standaloneServer which is strange).

Updated docs for the setup with the old backend system is still missing.

**Comment by gaelgoth** [comment]
Out of curiosity, can you tell me how you test the plugin on your instance? I would like to try your changes on our instance

**Comment by Roshick** [comment]
Of course, following https://backstage.io/docs/local-dev/linking-local-packages/ you just need to link the local packages in the root package.json.

Example:
```
"workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "../backstage-plugin-announcements/plugins/*"
    ]
  }
```

I would recommend to do this in a clean clone of your instance so that cached versions of the packages you want to test do not remain in any of the node_modules of the app, backend or any other package that use them as dependency.

**Review by gaelgoth — APPROVED** [review]
I performed some manual tests on our instance, and auth work as expected now. Thank you for the changes. I look forward to the next release

**Comment by kurtaking** [comment]
Hey @Roshick, thanks for the PR! We can get this merged once you've added a changeset.

**Comment by Roshick** [comment]
Hey @kurtaking, done!

**Review by kurtaking — APPROVED** [review]

**Comment by kurtaking** [comment]
@Roshick @gaelgoth this should be live on npm now.

**Pull request merged**
