### PR TITLE
Refactor announcements infoCard

### PR DESCRIPTION
**Pull request by gaelgoth**
Here is my proposal for #77.  The aim is to make something lighter and keep it on line with this infocard: https://github.com/procore-oss/backstage-plugin-announcements/blob/main/docs/images/announcements_card.png.

Here's what it looks like: 
image

Depending on your feedback @kurtaking , I'll do that next:
- [x] Update screenshot https://github.com/procore-oss/backstage-plugin-announcements/blob/main/README.md?plain=1#L36
- [x] Changeset

### CODE REVIEW

**Comment by kurtaking** [comment]
I'm not the biggest fan of this existing page in general, and I have a long-term hope of separating concerns into two areas.

1. **Announcements / Newsfeed** - where end users go to browse the latest announcements in a more social media newsfeed atmosphere. There are many opportunities to add functionality here, such as filtering by topic, read/unread, etc.

2. **Admin Panel** - where admins can manage announcements (create, edit, update, delete). I want a user to have all of this functionality on a single page instead. You are currently taken through several different react components to create and edit announcements (and categories).

Here are some screenshots from exploratory work I've done. Someone can manage announcements and categories from a single view.

image

image

and then some sort of scrollable newsfeed for end users

image

---

With all of that being said, I like the changes you are introducing to the existing components. Is it possible to move the edit menu to the top right of the card header? It looks like it's dangling at the end of the card with too much open space around it. Maybe something more similar to [this](https://v4.mui.com/components/cards/#complex-interaction)?

**Comment by gaelgoth** [comment]
I like your idea @kurtaking to have clear/distinct views between announcements and admin. Is it also scheduled to support different levels of announcements like `info`, `critical`, ...? Regarding this PR, yes, I can adapt as you mentioned 👍🏾. Thanks for the insight into the future of this plugin.

**Comment by kurtaking** [comment]
> Is it also scheduled to support different levels of announcements like info, critical, ...?

Yeah, it can. I've talked to @drodil about this some, as they had this open [PR](https://github.com/K-Phoen/backstage-plugin-announcements/pull/164) for that functionality. We just need to get it merged in over here.

I also want to create the concept of campaigns that can handle more targeted announcements based on something. 

For example, I want to be able to say, "Send this announcement to owners of components where type == API and label == something and X team is partOf Y division."

I plan to write up more formal issues on all of this in the _near_ future.

**Comment by kurtaking** [comment]
Hey @gaelgoth, the next release will include https://github.com/procore-oss/backstage-plugin-announcements/pull/105 which should help with local development. Our of curiosity, how are you currently populating local data for development?

**Comment by gaelgoth** [comment]
> Hey @gaelgoth, the next release will include #105 which should help with local development. Our of curiosity, how are you currently populating local data for development?

Hello @kurtaking 👋🏽,

Nice addition. Yes, I did it manually last time

**Comment by gaelgoth** [comment]
Rebase branch

**Comment by gaelgoth** [comment]
Hi @kurtaking, 

I did the changes as requested 👍🏾 

image

**Comment by kurtaking** [comment]
Hey @gaelgoth, I ran things locally, and the updates look great! Can you do one last thing and look for any screenshots that need to be updated? Looking forward to getting this merged.

**Comment by gaelgoth** [comment]
Hello @kurtaking,
Thank you for the review. I updated the screenshot.

**Comment by Nereis** [comment]
Hi @kurtaking,

Since you are refactoring the views, I'll would suggest to integrate the excerpt (that I would rename to description or summary which are more common terms) in the detail of the announcement.

**Comment by kurtaking** [comment]
> Hi @kurtaking,
> 
> Since you are refactoring the views, I'll would suggest to integrate the excerpt (that I would rename to description or summary which are more common terms) in the detail of the announcement.

Hey @Nereis, I saw you created an issue for this, correct? Happy to follow up there and get a separate PR going.

**Pull request merged**
