### PR TITLE
Able to delete announcement category

### PR DESCRIPTION
**Pull request by lavanya-sainik-ericsson**
Checklist:

* [X] I have updated the necessary documentation
* [X] I have signed off all my commits as required by [DCO](https://GitHub.com/apps/dco/)
* [X] My build is green

Signed-off-by: elavsai lavanya.sainik@ericsson.com

### CODE REVIEW

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

This is another PR, we wanted to propose as an improvement feature. Request your review / feedback here based on your availability and let me know if any comments :)

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Just a gentle reminder :)
Please let me know if you have any feedback/concerns based on your availability on this PR.

Thanks

**Comment by kurtaking** [comment]
@lavanya-sainik-ericsson, this has side effects on announcements associated with the category. 

When deleted, the announcement looks fine in the UI, but the record for it in the database never gets updated. I get errors when attempting to assign the existing announcement to a new category.

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Thanks for sharing your comments :) Have pushed the patch with updated changes.
Please let us know if you have any comments/concerns on these changes based on your availability :)

Thanks

**Review by kurtaking — APPROVED** [review]
We'll get this out in the next release 😃 🚢

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Thanks a lot for reviewing and merging this PR :)

**Pull request merged**
