### PR TITLE
Bug Fix: Creating a category with a different slug and title will prevent the announcement from being created #351

### PR DESCRIPTION
**Pull request by lavanya-sainik-ericsson**
Signed-off-by: elavsai lavanya.sainik@ericsson.com

Checklist:

* [X] I have updated the necessary documentation
* [X] I have signed off all my commits as required by [DCO](https://GitHub.com/apps/dco/)
* [X] My build is green

### CODE REVIEW

**Comment by gaelgoth** [comment]
We noticed the same issue on our side. Thanks for the fix 👍

**Review by gaelgoth — APPROVED** [review]

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Request your review for this PR based on your availability and let me know if any comments :)
  
[gaelgoth](https://github.com/gaelgoth), Thanks for the approval.

**Comment by kurtaking** [comment]
The behavior in the category field on the form is not what I'd expect it to be. It seems that when selecting an existing category, it populates the slug value and tries to create a new entry. 

Is that what you are experiencing? Sorry it's taken so long. I'm on limited capacity until the second week of July, but want to help get a fix merged this week.

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Thanks for your comment. Have updated the PR with the changes. Request your review  based on your availability and let me know if any further comments :)

[gaelgoth](https://github.com/gaelgoth), Thanks for the approval.

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Just a gentle reminder :) Have resolved the given comments.
Please let me know if you have any feedback/concerns based on your availability.

Thanks

**Comment by kurtaking** [comment]
> Hey [kurtaking](https://github.com/kurtaking),
> 
> Just a gentle reminder :) Have resolved the given comments. Please let me know if you have any feedback/concerns based on your availability.
> 
> Thanks

Hey @lavanya-sainik-ericsson, I apologize for being so slow to help but I am back and will dedicate some time this afternoon.

**Comment by kurtaking** [comment]
I have also opened this [issue](https://github.com/procore-oss/backstage-plugin-announcements/issues/373), which would help with situations like this in the future.

**Comment by kurtaking** [comment]
The lock file is out of sync here. I opened this [PR](https://github.com/procore-oss/backstage-plugin-announcements/pull/374) to verify.

**Comment by kurtaking** [comment]
👋🏼 checking in a bit earlier - I'll be on the lookout for a response in the next few hours. Otherwise, I'll help by merging the PR I created with the updated lock file.

**Comment by kurtaking** [comment]
Learned to push directly to your PR by following this [gist](https://gist.github.com/wtbarnes/56b942641d314522094d312bbaf33a81). I want to make sure you get credit for the contribution PR. 

Thank you, @lavanya-sainik-ericsson , for your patience and contribution 😄 :shipit:

**Review by kurtaking — APPROVED** [review]

**Comment by lavanya-sainik-ericsson** [comment]
Hey [kurtaking](https://github.com/kurtaking),

Thanks a lot for reviewing and merging this PR :)

**Pull request merged**
