### PR TITLE
fix: use correct api path on collector

### PR DESCRIPTION
**Pull request by gaelgoth**
On the scheduled collector task for the search feature, it tries to fetch announcements on `GET /api/announcements/` , which makes search entries empty.

To be taken into account when https://github.com/procore-oss/backstage-plugin-announcements/issues/23 is started 😄 

Observed logs on our Backstage instance:
```
12:57:48.461Z[22m [34mbackstage[39m [32minfo[39m ::ffff:127.0.0.1 - - [24/Oct/2023:12:57:48 +0000] "GET /api/announcements/ HTTP/1.1" 401 12 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" [36mtype[39m=incomingRequest
[1] [2m2023-10-24T12:57:48.474Z[22m [34msearch[39m [31merror[39m Collating documents for announcements failed: ResponseError: Request failed with 401 Error [36mtype[39m=plugin [36mdocumentType[39m=announcements
[1] [2m2023-10-24T12:57:48.474Z[22m [34mbackstage[39m [31merror[39m Request failed with 401 Error [36mtype[39m=taskManager [36mtask[39m=search_index_announcements [36mresponse[39m=[object Response] [36mbody[39m=[object Object] [36mcause[39m=Error: Request failed with status 401 Unauthorized, Unauthorized [36mname[39m=ResponseError [36mstack[39m=ResponseError: Request failed with 401 Error
[1]     at Function.fromResponse (/home/user/workspace/backstage/node_modules/@backstage/errors/dist/index.cjs.js:238:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at <anonymous> (/home/user/workspace/backstage/node_modules/@procore-oss/backstage-plugin-announcements-backend/dist/index.cjs.js:145:15)
[1]     at AnnouncementsClient.announcements (/home/user/workspace/backstage/node_modules/@procore-oss/backstage-plugin-announcements-backend/dist/index.cjs.js:151:12)
[1]     at AnnouncementCollatorFactory.execute (/home/user/workspace/backstage/node_modules/@procore-oss/backstage-plugin-announcements-backend/dist/index.cjs.js:171:21)
[1]     at async next (node:internal/streams/from:85:11)
[1] [2m2023-10-24T12:57:48.475Z[22m [34mbackstage[39m [90mdebug[39m task: search_index_announcements will next occur around 2023-10-24T15:07:48.474+02:00 [36mtype[39m=taskManager [36mtask[39m=search_index_announcements
```

### CODE REVIEW

**Comment by kurtaking** [comment]
Ah, I remember there being an [open PR](https://github.com/K-Phoen/backstage-plugin-announcements/pull/178) for this. My revert last night to have a 1:1 migration removed changes from a few open [PRs](https://github.com/K-Phoen/backstage-plugin-announcements/pulls) we will want to get merged.

Add a [changeset](https://github.com/procore-oss/backstage-plugin-announcements/blob/main/CONTRIBUTING.md#creating-changesets), and then we can 🚢 .

**Review by kurtaking — APPROVED** [review]
Thank you!

**Comment by gaelgoth** [comment]
I thought updating the API path was enough, but I still got errors. I will replicate the fix that you mentioned https://github.com/K-Phoen/backstage-plugin-announcements/pull/178/files.

```typescript
[1] [2m2023-10-25T06:19:26.812Z[22m [34mbackstage[39m [31merror[39m results is not iterable [36mtype[39m=taskManager [36mtask[39m=search_index_announcements [36mstack[39m=TypeError: results is not iterable
```

**Comment by kurtaking** [comment]
> I thought updating the API path was enough, but I still got errors. I will replicate the fix that you mentioned https://github.com/K-Phoen/backstage-plugin-announcements/pull/178/files.
> 
> ```ts
> [1] [2m2023-10-25T06:19:26.812Z[22m [34mbackstage[39m [31merror[39m results is not iterable [36mtype[39m=taskManager [36mtask[39m=search_index_announcements [36mstack[39m=TypeError: results is not iterable
> ```

@gaelgoth let me know how that's going and if we need to track it somewhere.

**Comment by gaelgoth** [comment]
Fixed there: https://github.com/procore-oss/backstage-plugin-announcements/pull/86

**Pull request merged**
