### PR TITLE
feat(Internationalization): adds support for internationalization

### LINKED ISSUE #491: 🚀 Feature: add internationalization support
### 🔖 Feature description

I’d like to suggest adding support for internationalization as described in the [Backstage docs](https://backstage.io/docs/plugins/internationalization/).

Backstage itself has already started adding some support in the [user-settings plugin](https://github.com/backstage/backstage/tree/master/plugins/user-settings).

If this is not something you would consider doing but are willing to accept a PR for, I (or someone on my team) may be able to work on it.

Thanks for the great plugin.

### 🎤 Context

In my use-case, most of our users are not native english speakers, and this would help us have a better consistency in our IDP/Backstage instance without having to clone the repo.

### ✌️ Possible Implementation

Follow instructions in the [Backstage docs](https://backstage.io/docs/plugins/internationalization/).

And if it helps, I did submit a PR into the [Toolbox Plugin](https://github.com/drodil/backstage-plugin-toolbox/pull/125), it could be used as a 'guide'.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by LucasTemponi**
### Summary 📰

  Adds support for internationalization

### Details 📚

   Implements internationalization following [Backstage's guidelines](https://backstage.io/docs/plugins/internationalization/)
   Closes #491

#### Checklist ✅

- [x] I have updated the necessary documentation
- [x] I have signed off all my commits as required by [DCO](https://GitHub.com/apps/dco/)
- [x] My build is green

### CODE REVIEW

**Comment by kurtaking** [comment]
@LucasTemponi, the DCO step is failing. We can get this merged once you get that fixed.

**Comment by LucasTemponi** [comment]
@kurtaking , commits signed off.

Sorry about that.

**Comment by kurtaking** [comment]
> @kurtaking, anything else we need to do on our side?

Taking a look now - I've been out the past two weeks.

**Comment by kurtaking** [comment]
@LucasTemponi @gabrielcbe - sorry for the delay. This will be in the next release.

**Review by kurtaking — APPROVED** [review]

**Comment by gabrielcbe** [comment]
> @LucasTemponi @gabrielcbe - sorry for the delay. This will be in the next release.

No worries about the delay, thanks a lot for taking the time to review and merge the PR

**Pull request merged**
