### PR TITLE
Fix paging not working on AnnouncementsPage

### PR DESCRIPTION
**Pull request by ericcerfonteyn**
Checklist:

* [x] I have updated the necessary documentation
* [x] I have signed off all my commits as required by [DCO](https://GitHub.com/apps/dco/)
* [ ] My build is green

### CODE REVIEW

**Comment by markyjones** [comment]
Hey @kurtaking  👋 Sorry for the direct nudge but we are keen to get this fix in and avoid running a fork for much longer. Does this fix look OK to you? 🙏

**Review by kurtaking — DISMISSED** [review]

**Comment by kurtaking** [comment]
> Hey @kurtaking  👋 Sorry for the direct nudge but we are keen to get this fix in and avoid running a fork for much longer. Does this fix look OK to you? 🙏 

Hey 👋 thank you for the fix and apologize for the delay. We'll get this out in a release soon.

**Comment by ericcerfonteyn** [comment]
@kurtaking found and fixed a tsc issue.

**Review by kurtaking — APPROVED** [review]

**Comment by kurtaking** [comment]
> @kurtaking found and fixed a tsc issue.

@ericcerfonteyn last commit contains DCO error.

**Comment by ericcerfonteyn** [comment]
🤦 thanks, fixed!

**Review by kurtaking — APPROVED** [review]

**Pull request merged**
