### PR TITLE
Added property variant to AnnouncementsCard

### PR DESCRIPTION
**Pull request by benjidotsh**
This allows you to override the default value `gridItem`, which is useful when using the card on a homepage for example. (otherwise it adds a margin to the bottom of the card, making the card inconsistent in size compared to the others)

Checklist:

* [x] I have updated the necessary documentation
* [x] I have signed off all my commits as required by [DCO](https://GitHub.com/apps/dco/)
* [x] My build is green

### CODE REVIEW

**Review by kurtaking — APPROVED** [review]
Hey, this change looks good to me and adds some nice flexibility for the adopter. 👍🏼 thanks for contributing!

**Comment by ssliman** [comment]
when can we expect a release for above? @kurtaking

**Comment by benjidotsh** [comment]
@ssliman This repository uses changesets, so it should have triggered a release on merge. According to the [changelog](https://github.com/procore-oss/backstage-plugin-announcements/blob/main/plugins/announcements/CHANGELOG.md), this change should have been released in 0.6.2

**Comment by ssliman** [comment]
@benjidotsh thanks for the update

**Pull request merged**
